version: '3'

services:
  postgres:
    container_name: receiptfox-postgres
    image: postgres:13.4
    ports:
      - "5432:5432"
  docsrabbit:
    container_name: receiptfox-docsrabbit
    image: registry.gitlab.com/encircle360-oss/docsrabbit/docsrabbit:v0.0.6
    ports:
      - "50005:50005"
      - "51005:51005"
    environment:
      - SPRING_PROFILES_ACTIVE=mongo
      - MONGO_URI=mongodb://receiptfox-mongodb:27017/docsrabbit
      - MONGO_DATABASE=docsrabbit
  mongo:
    container_name: receiptfox-mongodb
    image: mongo:4
    ports:
      - "27017:27017"
