spring:
  mvc:
    locale: en_US
  datasource:
    url: jdbc:postgresql://localhost:5432/receiptfox
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  error:
    include-binding-errors: always
  servlet:
    encoding:
      force: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

s3:
  endpoint: "http://localhost:9000"
  sigv4: "us-west-1"
  accessKey: "access_key"
  secretKey: "secret_key"
  bucket: "default"
